captainVersion: 4
services:
    $$cap_appname-mapa-mapasculturais:
        image: softagon/mapasculturais:$$cap_mapasculturais_tag
        restart: unless-stopped
        volumes:
            - $$cap_appname-mapa-assets:/var/www/html/assets
            - $$cap_appname-mapa-public-files:/var/www/html/files
            - $$cap_appname-mapa-private-files:/var/www/var/private-files
            - $$cap_appname-mapa-saas-files:/var/www/var/saas-files
            - $$cap_appname-mapa-sessions:/var/www/var/sessions
            - $$cap_appname-mapa-logs:/var/www/var/logs
        environment:
            APP_MODE: $$cap_app_mode
            LOG_LEVEL: $$cap_log_level
            LOG_ENABLED: $$cap_log_enabled
            CEP_TOKEN: $$cap_cep_token
            MAILER_TRANSPORT: $$cap_mailer_transport
            MAILER_FROM: $$cap_mailer_from
            MAILER_ALWAYSTO: $$cap_mailer_alwaysto
            DB_HOST: srv-captain--$$cap_appname-mapa-db
            DB_NAME: $$cap_postgres_db
            DB_USER: $$cap_postgres_user
            DB_PASS: $$cap_postgres_password
            GOOGLE_RECAPTCHA_SITEKEY: $$cap_google_recaptcha_sitekey
            GOOGLE_RECAPTCHA_SECRET: $$cap_google_recaptcha_secret
            PENDING_PCACHE_RECREATION_INTERVAL: $$cap_pending_pcache_recreation_interval
            JOBS_INTERVAL: $$cap_jobs_interval
            LOGO_IMAGE: $$cap_logo_image
            LOGO_HIDELABEL: $$cap_logo_hidelabel
            BUILD_ASSETS: $$cap_build_assets
            SMTP_LOGIN: $$cap_smtp_login
            SMTP_PASSWORD: $$cap_smtp_password
            SMTP_HOST: $$cap_smtp_host
            SMTP_PORT: $$cap_smtp_port
            AUTH_SALT: $$cap_auth_salt
            AUTH_GOOGLE_CLIENT_ID: $$cap_google_client_id
            AUTH_GOOGLE_CLIENT_SECRET: $$cap_google_client_secret
        depends_on:
            - $$cap_appname-mapa-db

    $$cap_appname-mapa-db:
        image: softagon/mapasculturais-db:latest
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_USER: $$cap_postgres_user
            POSTGRES_DB: $$cap_postgres_db
        volumes:
            - $$cap_appname-mapa-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
        - description: Versão do MAPA em https://hub.docker.com/r/softagon/mapasculturais
          defaultValue: prefeitura-
          id: $$cap_mapasculturais_tag
          label: Tag docker da versão
          validRegex: /.{1,}/

        - id: $$cap_postgres_password
          label: PostgreSQL Password
          defaultValue: $$cap_gen_random_hex(16)
          description: 'A senha do usuário do banco de dados PostgreSQL.'
          validRegex: /.{1,}/

        - id: $$cap_postgres_user
          label: PostgreSQL User
          defaultValue: mapas
          description: 'O usuário do banco de dados PostgreSQL.'
          validRegex: /^([a-zA-Z0-9\-\.\_])+$/

        - id: $$cap_postgres_db
          label: PostgreSQL Database
          defaultValue: mapas
          description: 'O nome do banco de dados PostgreSQL.'
          validRegex: /^([a-zA-Z0-9\-\.\_])+$/

        - id: $$cap_base_url
          label: Base URL
          defaultValue: 'https://$$cap_appname.$$cap_root_domain'

        - id: $$cap_app_mode
          label: App Mode
          defaultValue: production

        - id: $$cap_log_level
          label: Log Level
          defaultValue: DEBUG

        - id: $$cap_log_enabled
          label: Log Enabled
          defaultValue: 'true'

        - id: $$cap_cep_token
          label: CEP Token
          defaultValue: ''

        - id: $$cap_mailer_transport
          label: Mailer Transport
          defaultValue: smtp://localhost:25

        - id: $$cap_mailer_from
          label: Mailer From
          defaultValue: suporte@meumapa.gov.br

        - id: $$cap_mailer_alwaysto
          label: Mailer Always To
          defaultValue: ''

        - id: $$cap_google_recaptcha_sitekey
          label: Google Recaptcha Site Key
          defaultValue: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI

        - id: $$cap_google_recaptcha_secret
          label: Google Recaptcha Secret
          defaultValue: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

        - id: $$cap_pending_pcache_recreation_interval
          label: Pending Pcache Recreation Interval
          defaultValue: '1'

        - id: $$cap_jobs_interval
          label: Jobs Interval
          defaultValue: '1'

        - id: $$cap_logo_image
          label: Logo Image
          defaultValue: img/logo-mapas.png

        - id: $$cap_logo_hidelabel
          label: Logo Hide Label
          defaultValue: 'true'

        - id: $$cap_build_assets
          label: Build Assets
          defaultValue: '0'

        - id: $$cap_smtp_login
          label: SMTP Login
          defaultValue: email@gmail.com

        - id: $$cap_smtp_password
          label: SMTP Password
          defaultValue: $$cap_gen_random_hex(16)

        - id: $$cap_smtp_host
          label: SMTP Host
          defaultValue: smtp.gmail.com

        - id: $$cap_smtp_port
          label: SMTP Port
          defaultValue: '587'

        - id: $$cap_auth_salt
          label: Auth Salt
          defaultValue: $$cap_gen_random_hex(36)

        - id: $$cap_auth_google_client_id
          label: Auth Google Client ID
          defaultValue: ''

        - id: $$cap_auth_google_client_secret
          label: Auth Google Client Secret
          defaultValue: $$cap_gen_random_hex(36)

    instructions:
        start: |-
            Mapas Culturais é uma plataforma colaborativa que reúne informações sobre agentes, espaços, eventos e projetos culturais.
        end: >
            Mapas Culturais está implantado e disponível.
    displayName: Mapas Culturais
    isOfficial: false
    description: Mapas Culturais é uma iniciativa cívica de criação de ferramentas de gestão cultural.
    documentation: 'https://github.com/SoftagonSistemas/mapasculturais'
