 
services:
  mapasculturais:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: softagon/mapasculturais:dev
  db:
    build:
      context: ./
      dockerfile: docker/Dockerfile-db
    image: softagon/mapasculturais-db:dev
