services:
  mapasculturais:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.env:/.env
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      - ./docker-data/saas-files:/var/www/var/saas-files
      - ./docker-data/sessions:/var/www/var/sessions
      - ./docker-data/logs:/var/www/var/logs
      - ./custom/modules/:/var/www/src/modules/
    links:
      - db
      - redis
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - db
      - redis
    environment:
      - REDIS_CACHE=redis
      - REDIS_SESSION_PORT=6379
      - SESSIONS_SAVE_PATH=tcp://redis:6379

  db:
    image: softagon/mapasculturais-db:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  redis:
    image: redis:6.2.14
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: