# name: Docker Image CI

# on:
#   push:
#     branches: ['*']
#   pull_request:
#     branches: ['*']

# permissions:
#   contents: write
#   packages: write
#   issues: write
#   pull-requests: write

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Extract branch name
#         id: extract_branch
#         run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build and push Docker image 1 (mapasculturais)
#         run: |
#           docker build --no-cache -t softagon/mapasculturais:${{ env.branch_name }} -f docker/Dockerfile .
#           docker push softagon/mapasculturais:${{ env.branch_name }}

#       - name: Build and push Docker image 2 (mapasculturais-db)
#         run: |
#           docker build --no-cache -t softagon/mapasculturais-db:${{ env.branch_name }} -f docker/Dockerfile-db .
#           docker push softagon/mapasculturais-db:${{ env.branch_name }}

#       - name: Get commit message
#         id: get_commit_message
#         run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

#       - name: Create GitHub Release
#         if: ${{ success() }}
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ env.branch_name }}
#           release_name: Release ${{ env.branch_name }}
#           body: |
#             ## Changes
#             - Docker image version ${{ env.branch_name }} released.
#             - Commit message: ${{ env.COMMIT_MESSAGE }}
#           draft: false
#           prerelease: false
